name: Build Windows App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dart SDK
      run: |
        $dartUrl = "https://storage.googleapis.com/dart-archive/channels/stable/release/3.4.0/sdk/dartsdk-windows-x64-release.zip"
        Write-Host "Downloading Dart SDK from: $dartUrl"
        Invoke-WebRequest -Uri $dartUrl -OutFile "dart-sdk.zip"
        Write-Host "Extracting Dart SDK..."
        Expand-Archive -Path "dart-sdk.zip" -DestinationPath "C:\dart-sdk" -Force
        $dartPath = "C:\dart-sdk\dart-sdk\bin"
        [System.Environment]::SetEnvironmentVariable("Path", $dartPath + ";" + [System.Environment]::GetEnvironmentVariable("Path", [System.EnvironmentVariableTarget]::Process), [System.EnvironmentVariableTarget]::Machine)
        echo "$dartPath" >> $env:GITHUB_PATH
        Write-Host "Added Dart SDK path: $dartPath"
    
    - name: Verify Dart SDK Installation
      run: |
        Write-Host "Current PATH: $env:Path"
        Write-Host "Checking Dart version..."
        dart --version
        $dartVersion = dart --version
        if (-not ($dartVersion -match "3.4.0")) {
          Write-Error "Dart version 3.4.0 is required, but found: $dartVersion"
          exit 1
        }
        Write-Host "Dart SDK installation verified successfully"
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
        cache: true
        cache-key: flutter-windows-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
    
    - name: Verify Flutter version
      run: |
        Write-Host "Checking Flutter version..."
        flutter --version
        $flutterVersion = flutter --version
        if (-not ($flutterVersion -match "3.19.3")) {
          Write-Error "Flutter version 3.19.3 is required, but found: $flutterVersion"
          exit 1
        }
        Write-Host "Flutter installation verified successfully"
    
    - name: Install dependencies
      run: |
        Write-Host "Installing dependencies..."
        flutter pub get
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to install dependencies"
          exit 1
        }
        Write-Host "Dependencies installed successfully"
    
    - name: Build Windows App
      run: flutter build windows --release
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/runner/Release/
        if-no-files-found: error 