name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t flutter-windows-builder .

    - name: Run build in container
      run: |
        docker run --rm -v ${PWD}:/app flutter-windows-builder

    - name: Upload MSIX package
      uses: actions/upload-artifact@v4
      with:
        name: windows-msix
        path: build/windows/msix/*.msix 