name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        $imageName = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        docker build -t $imageName .
        docker push $imageName

    - name: Run build in container
      run: |
        docker run --rm -v ${PWD}:/app ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    - name: Upload MSIX package
      uses: actions/upload-artifact@v4
      with:
        name: windows-msix
        path: build/windows/msix/*.msix 