name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
        cache: true
        cache-key: 'flutter-windows-3.19.3-'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows app
      run: flutter build windows --release

    - name: Create MSIX package
      run: |
        flutter pub add msix
        flutter pub get
        flutter pub run msix:create --display-name "Kaatje" --publisher-display-name "Your Publisher Name" --identity-name "com.yourdomain.kaatje" --publisher "CN=YourPublisherID" --logo "assets/images/icon.png" --version "1.0.0.0"

    - name: Upload MSIX package
      uses: actions/upload-artifact@v4
      with:
        name: windows-msix
        path: build/windows/msix/*.msix 