name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    
    - name: Install Dart SDK
      run: |
        Write-Host "Installing Dart SDK version 3.4.0..."
        choco install dart-sdk --version=3.4.0 -y
        refreshenv
        
        # Set the correct Dart SDK path
        $dartPath = "C:\tools\dart-sdk\bin"
        
        # Add Dart SDK path to the current session and system PATH
        $env:Path = "$dartPath;$env:Path"
        [System.Environment]::SetEnvironmentVariable("Path", "$dartPath;$env:Path", [System.EnvironmentVariableTarget]::Machine)
        
        Write-Host "Added Dart SDK path: $dartPath"
        
        # Verify Dart installation
        if (!(Get-Command dart -ErrorAction SilentlyContinue)) {
            Write-Host "Current PATH: $env:Path"
            Write-Host "Checking if dart.exe exists at $dartPath"
            if (Test-Path "$dartPath\dart.exe") {
                Write-Host "dart.exe found at $dartPath"
            } else {
                Write-Host "dart.exe not found at $dartPath"
            }
            Write-Error "Dart command not found after installation."
            exit 1
        }
        
        $dartVersion = dart --version
        Write-Host "Dart SDK version $dartVersion installed successfully"
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
        cache: true
    
    - name: Switch to Flutter version with Dart 3.4.0
      run: |
        Write-Host "Switching to Flutter version with Dart 3.4.0..."
        flutter version 3.19.3
        if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to switch Flutter version"
            exit 1
        }
    
    - name: Verify Flutter and Dart versions
      run: |
        Write-Host "Checking Flutter version..."
        flutter --version
        Write-Host "Checking Dart version..."
        dart --version
        $dartVersion = dart --version
        if (-not ($dartVersion -match "3.4.0")) {
            Write-Error "Dart version 3.4.0 is required, but found: $dartVersion"
            exit 1
        }
        Write-Host "Flutter and Dart versions verified successfully"
    
    - name: Install dependencies
      run: |
        Write-Host "Installing dependencies..."
        flutter pub get
        if ($LASTEXITCODE -ne 0) {
          Write-Error "Failed to install dependencies"
          exit 1
        }
        Write-Host "Dependencies installed successfully"
    
    - name: Build Windows app
      run: flutter build windows --release
    
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/windows/runner/Release/
        if-no-files-found: error 